### ISSUE TITLE
CI/Releases Support

### ISSUE THREAD

**Issue by cr1901** [jbrandwood/v810-gcc#1]
When I get around to it, I'd be more than happy to add Travis CI and Releases Support. This will make downloading a `v810-gcc` toolchain for multiple OSes as simple as going to the [releases](https://github.com/jbrandwood/v810-gcc/releases) page.

I just want to gauge as to whether it's something you'd be interested in?

**Comment by jbrandwood** [comment]
Hi, and thank-you for your interest in the project! :-)

If you are still using the code, may I ask if you still believe that providing Travis CI and Realeases support is a good idea?

From my limited POV, the V810-GCC project is not useful by itself (IMHO) without the supporting libraries and build systems for the two consoles that use the V810 CPU.

The VUEngine developers already provide their own fork of this compiler for their VirtualBoy development system, and I don't think that PC-FX developers are really ready for a pre-built compiler (yet).

Am I missing something?

Best wishes,

John

**Comment by cr1901** [comment]
@jbrandwood While I'm am still interested in principle in v810-gcc releases, a lot has changed since Mar 2019 (and it wasn't _just_ the pandemic) that's made this a much longer-term goal than intended. I basically wanted an easy place to download a v810 toolchain without having to comb PlanetVB forum posts for when gcc gets updated.

I see that gcc 10 is being used now. Does the backend use [mode CC](https://gcc.gnu.org/wiki/CC0Transition) representation? I would genuinely be curious to see how the gcc backend works with Rust once that's ready (as well keeping up to date with upstream binutils).

Anyways, feel free to close. These are idle thoughts, I totally forgot I opened this issue, and I don't have anything specific in mind anymore :).
