### ISSUE TITLE
Compiling on Linux (Ubuntu variant)

### ISSUE THREAD

**Issue by junglira** [jbrandwood/v810-gcc#2]
When attempting to build using the build build_compiler.sh on Linux, I'd run into unknown command issues due to the program calls having the Windows flavored ".exe" extension. Using a find and replace to remove the ".exe" extension from calls to programs such as curl allowed the script to work as expected.

Perhaps having variables holding the name of the program with or without the extension depending on the OS could be a good solution for this. Though MSYS2 may possibly not need the .exe extension either, as I've previously used Cygwin and was not required to specify the executable extension when using it. If so, removing the extension altogether would be the simplest approach.

**Comment by jbrandwood** [comment]
Thank you for the report, this is something that I should fix!

I guess that I didn't think that anyone would use the overall build script on Linux, because I always just use the individual seperate scripts so that I can find and fix errors ... whoops!

**Comment by jbrandwood** [comment]
Thanks for reporting this, it has finally been fixed. :-)
