### ISSUE TITLE
no longer compatible with liberis due to linker script after v810.x fix therein

### ISSUE THREAD

**Issue by enthusi** [jbrandwood/v810-gcc#5]
It seems to me (after I had some help troubleshooting this), that the fixes that made it into the v810.x linkerscript of liberis are no longer compatible with the present v810-ld linker script:
https://github.com/jbrandwood/liberis/commit/313b93be1b3a8ffc0b8dbbfa4ca0503df3b5aeea
While re-compiling v810-ld with the linkerscript of liberis solved this issue for me, I can not judge any side-effects this may have on other things dependent on this wonderful tool-chain.

**Comment by jbrandwood** [comment]
The build scripts have been updated, and the new binutils2.27 uses the same script as liberis.

This should be fixed now.

**Comment by jbrandwood** [comment]
BTW ... I'm still updating the scripts and need to update the project's README.

**Comment by jbrandwood** [comment]
All done!
